# Generated by Django 6.0 on 2025-12-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=100)),
                ('ngaysinh', models.DateField()),
                ('gioitinh', models.CharField(max_length=10)),
                ('dantoc', models.CharField(max_length=50)),
                ('tongiao', models.CharField(blank=True, max_length=50, null=True)),
                ('cccd', models.CharField(max_length=20, unique=True)),
                ('ngaycap', models.DateField()),
                ('noicap', models.CharField(max_length=100)),
                ('nghenghiep', models.CharField(blank=True, max_length=100, null=True)),
                ('ghichu', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
