# Generated by Django 6.0 on 2025-12-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hokhau', '0001_initial'),
        ('khoanthu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NopTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoinoptien', models.CharField(max_length=100)),
                ('sotien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ngaynop', models.DateField(blank=True, null=True)),
                ('hokhau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hokhau.hokhau')),
                ('khoanthu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khoanthu.khoanthu')),
            ],
        ),
    ]
