# Generated by Django 6.0 on 2025-12-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nhankhau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sohokhau', models.CharField(max_length=20, unique=True)),
                ('sonha', models.CharField(max_length=100)),
                ('duong', models.CharField(max_length=100)),
                ('phuong', models.CharField(max_length=100)),
                ('quan', models.CharField(max_length=100)),
                ('ngaylamhokhau', models.DateField()),
                ('sothanhvien', models.IntegerField()),
                ('ghichu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('chuhokhau', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='nhankhau.nhankhau')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuThayDoiHoKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaithaydoi', models.IntegerField(choices=[(1, 'Them thanh vien'), (2, 'Xoa thanh vien')])),
                ('ngaythaydoi', models.DateTimeField()),
                ('hokhau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hokhau.hokhau')),
                ('nhankhau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nhankhau.nhankhau')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhVienHoKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanhevoichuho', models.CharField(max_length=100)),
                ('ngaythemnhankhau', models.DateField()),
                ('hokhau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hokhau.hokhau')),
                ('nhankhau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nhankhau.nhankhau')),
            ],
        ),
    ]
